### PR TITLE
Image v2: Vendor Update and Logging Fix

### LINKED ISSUE #289: openstack_images_image_v2 does not set property
### Terraform Version
Latest 0.11.7, with latest openstack provider 1.3.

### Affected Resource(s)

- openstack_images_image_v2

### Terraform Configuration Files

Relevant parts pasted below:

```hcl
resource "openstack_images_image_v2" "images" {
  name = "${element(var.images, count.index)}"
  image_source_url = "${var.image_locations["${element(var.images, count.index)}"]}"
  count = "${length(var.images)}"
  container_format = "bare"
  disk_format = "qcow2"
  properties {
    hw_rng_model = "virtio"
  }
}```

Variables are defined as follows:

```hcl
variable "images" {
  description = "list of images to be uploaded to Glance, leave default for all"
  default = ["centos7", "opensuse423"]
  type = "list"
}

variable "image_locations" {
  description = "list of locations to download images, override to add custom ones"
  default = {
    centos7 = "http://w3.nue.suse.com/~smoioli/sumaform-images/openstack/centos7.qcow2"
    opensuse423 = "https://download.opensuse.org/repositories/systemsmanagement:/sumaform:/images:/openstack/images/opensuse423.x86_64.qcow2"
  }
  type = "map"
}
```

### Debug Output
https://gist.github.com/moio/cf242b87b84ca2aa186ec08b1fb96f80

### Expected Behavior

Image property `hw_rng_model` should be set to `virtio`, at next terraform plan nothing should be done.

### Actual Behavior

Image property `hw_rng_model` is not set and next terraform plan signals the change again.

Note that setting the property via the `openstack` client works, provided it is specified in single quotes:

```
openstack image set --property hw_rng_model='virtio' <UUID>
```

### Steps to Reproduce
1. `terraform apply`

### PR DESCRIPTION
**Pull request by jtopjian**
This PR updates the Gophercloud library for handling images. This might help #289, but I'm not sure yet.

If it doesn't, I have modified the debug logger to not print non-JSON requests. This will prevent the binary output from being logged when uploading images which will help with debugging this issue further.

### CODE REVIEW

**Comment by animationzl** [comment]
recheck

File: openstack/types.go [hunk 1]
```diff
@@ -88,8 +88,6 @@ func (lrt *LogRoundTripper) logRequest(original io.ReadCloser, contentType strin
 	if strings.HasPrefix(contentType, "application/json") {
 		debugInfo := lrt.formatJSON(bs.Bytes())
 		log.Printf("[DEBUG] OpenStack Request Body: %s", debugInfo)
-	} else {
-		log.Printf("[DEBUG] OpenStack Request Body: %s", bs.String())
```
Comment (fatmcgav) [inline openstack/types.go]: @jtopjian Do we loose any useful logging elsewhere by dropping this line? 

I wonder whether it's worth truncating the body at a certain length maybe?

Comment (fatmcgav) [reply openstack/types.go]: Yeh, that's true on terminal screw up...
