### PR TITLE
Compute v2: Flavor is_public Fix

### LINKED ISSUE #164: Openstack flavor is_public property not handled properly
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
ubuntu@controller:~/terraform$ ./terraform -v
Terraform v0.11.0
+ provider.openstack v1.0.0

### Affected Resource(s)
- openstack_compute_flavor_v2

```
### Terraform Configuration Files
provider "openstack" {
  user_name   = "admin"
  tenant_name = "admin"
  password    = "xxx"
  auth_url    = "http://localhost:5000/v2.0"
  region      = "RegionOne"
}

# flavors
resource "openstack_compute_flavor_v2" "light-flavor" {
  name  = "test"
  ram   = "64"
  vcpus = "1"
  disk  = "1"
  is_public = "true"
}
```

### Debug Output
link to the Gist.
https://gist.github.com/anonymous/720adac2ec5a06ba5735ddbb4a2eec59

### Expected Behavior
Flavor created ONCE on first run

### Actual Behavior
Flavor ALWAYS recreated as terraform think that is_public is changed 'false=>true'
even flavor create properly and shown as public in Openstack.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Openstack Ocata is used on Ubuntu Xenial.
openstack shows created flavor as:

```
root@controller:/root# openstack flavor show test
+----------------------------+--------------------------------------+
| Field                      | Value                                |
+----------------------------+--------------------------------------+
| OS-FLV-DISABLED:disabled   | False                                |
| OS-FLV-EXT-DATA:ephemeral  | 0                                    |
| access_project_ids         | None                                 |
| disk                       | 1                                    |
| id                         | fc1aea03-1913-40d7-9120-3bdb1bca37b1 |
| name                       | test                                 |
| os-flavor-access:is_public | True                                 |
| properties                 |                                      |
| ram                        | 64                                   |
| rxtx_factor                | 1.0                                  |
| swap                       |                                      |
| vcpus                      | 1                                    |
+----------------------------+--------------------------------------+
```

It seems terraform can not read is_public properly as it is namespaced by 'os-flavor-access:'

### PR DESCRIPTION
**Pull request by jtopjian**
Fixes #164

### CODE REVIEW

File: openstack/resource_openstack_compute_flavor_v2_test.go [hunk 1]
```diff
@@ -93,6 +93,8 @@ func testAccComputeV2Flavor_basic(flavorName string) string {
       ram = 2048
       vcpus = 2
       disk = 5
+
```
Comment (fatmcgav) [inline openstack/resource_openstack_compute_flavor_v2_test.go]: Extra line necessary?

Comment (jtopjian) [reply openstack/resource_openstack_compute_flavor_v2_test.go]: It's not necessary, but it was deliberate :)

My intention was to make the `is_public` field more explicit.

Comment (fatmcgav) [reply openstack/resource_openstack_compute_flavor_v2_test.go]: Good enough reason for me...
