### PR TITLE
Networking V2: fix fip disassociating on description update

### LINKED ISSUE #605: Networking V2: Floating IP description update causes port disassociation
It is caused by a conflict of `openstack_compute_floatingip_associate_v2` and `openstack_networking_floatingip_v2` or `openstack_networking_floatingip_associate_v2`. And #534 PR.

Test case:

```hcl
resource "openstack_compute_instance_v2" "instance_1" {
  name = "instance_1"
  security_groups = ["default"]
  network {
    uuid = "%networkuuid%"
  }
}

resource "openstack_networking_floatingip_v2" "floatingip_1" {
  pool        = "pool"
  subnet_id   = "%subnet%"
  description = "test" # <- comment out on the next run
}

resource "openstack_compute_floatingip_associate_v2" "floatingip_app" {
  floating_ip = "${openstack_networking_floatingip_v2.floatingip_1.address}"
  instance_id = "${openstack_compute_instance_v2.instance_1.id}"
}
```

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #605 

Will run tests first, then will push the fix

### CODE REVIEW

**Comment by kayrus** [comment]
@jtopjian ready for review.

File: openstack/resource_openstack_networking_floatingip_v2.go [hunk 1]
```diff
@@ -203,9 +203,13 @@ func resourceNetworkFloatingIPV2Update(d *schema.ResourceData, meta interface{})
 		hasChange = true
 		description := d.Get("description").(string)
 		updateOpts.Description = &description
+
+		// PortID is a pointer and not omitted, should always be set
```
Comment (jtopjian) [inline openstack/resource_openstack_networking_floatingip_v2.go]: Would the correct way of fixing this be to update Gophercloud?

Comment (kayrus) [reply openstack/resource_openstack_networking_floatingip_v2.go]: gophercloud updated
